import type { FinanceState } from "./types";

export const seedState: FinanceState = {
  current_cash: 4247.56,
  cash_accounts: [
    { id: "account-bank", title: "Bank visible balance", amount: 1.18, include_in_safe: true },
    { id: "account-other", title: "Other account balance", amount: 4246.38, include_in_safe: true },
  ],
  assets: [
    {
      id: "asset-binance",
      title: "Binance USDT Asset",
      amount: 300,
      currency: "USDT",
      include_in_safe: false,
      notes: "Investment asset only. Not included in Safe to Spend.",
    },
  ],
  settings: {
    survival_buffer: 500,
    salary_day: 1,
    currency: "AED",
    theme: "light",
    profile_version: 3,
  },
  incomes: [
    {
      id: "income-salary",
      title: "Monthly Salary",
      amount: 8000,
      source: "Salary",
      income_date: "2026-05-01",
      is_recurring: true,
      notes: "Salary repeats monthly.",
    },
  ],
  expenses: [],
  debts: [
    {
      id: "debt-sukuk",
      title: "Sukuk Finance Loan",
      total_amount: 45000,
      remaining_amount: 40266.67,
      monthly_payment: 1610.67,
      due_date: "2026-05-30",
      due_day: 30,
      reminder_day: 29,
      priority: "high",
      debt_type: "Finance Loan",
      icon: "bank",
      status: "active",
      notes: "Monthly installment goes every month. Keep reminder one day early.",
    },
    {
      id: "debt-noon",
      title: "ENBD Noon Credit Card",
      total_amount: 3714.05,
      remaining_amount: 3714.05,
      used_amount: 3714.05,
      monthly_payment: 0,
      due_day: 10,
      reminder_day: 9,
      priority: "high",
      debt_type: "Credit Card",
      icon: "card",
      status: "active",
    },
    {
      id: "debt-mastercard",
      title: "Emirates NBD Titanium Mastercard",
      total_amount: 6914.84,
      remaining_amount: 6914.84,
      used_amount: 6914.84,
      monthly_payment: 0,
      due_day: 3,
      reminder_day: 2,
      priority: "high",
      debt_type: "Credit Card",
      icon: "card",
      status: "active",
    },
    {
      id: "debt-aafaq",
      title: "Aafaq Credit Card",
      total_amount: 10000.9,
      remaining_amount: 1376,
      used_amount: 1376,
      available_limit: 8624.9,
      total_limit: 10000.9,
      monthly_payment: 0,
      priority: "high",
      debt_type: "Credit Card",
      icon: "card",
      status: "active",
    },
    {
      id: "debt-tabby-statement",
      title: "Tabby Statement",
      total_amount: 1604.54,
      remaining_amount: 1604.54,
      monthly_payment: 1604.54,
      due_date: "2026-06-02",
      priority: "high",
      debt_type: "Tabby / Installment",
      icon: "tabby",
      status: "active",
    },
    {
      id: "debt-tabby-later",
      title: "Tabby Pay Later / Installments",
      total_amount: 892.17,
      remaining_amount: 892.17,
      monthly_payment: 0,
      priority: "high",
      debt_type: "Installment",
      icon: "tabby",
      status: "active",
    },
    {
      id: "debt-office",
      title: "Office Loan / Office Balance",
      total_amount: 4000,
      remaining_amount: 4000,
      monthly_payment: 500,
      due_day: 1,
      reminder_day: 1,
      priority: "medium",
      debt_type: "Office Loan",
      icon: "office",
      status: "active",
      notes: "AED 500 monthly deduction from salary.",
    },
  ],
  payments: [
    { id: "pay-rent-may", title: "Rent Payment", amount: 4200, due_date: "2026-05-10", status: "unpaid", category: "Rent", priority: "critical", is_recurring: true, recurring_day: 10, reminder_day: 9, notes: "This should be paid from the current NBD/bank balance." },
    { id: "pay-mastercard-may", debt_id: "debt-mastercard", title: "Emirates NBD Titanium Reminder", amount: 6914.84, due_date: "2026-05-02", status: "unpaid", is_recurring: true, recurring_day: 2 },
    { id: "pay-noon-may", debt_id: "debt-noon", title: "ENBD Noon Card Reminder", amount: 3714.05, due_date: "2026-05-09", status: "unpaid", is_recurring: true, recurring_day: 9 },
    { id: "pay-office-may", debt_id: "debt-office", title: "Office Loan Deduction", amount: 500, due_date: "2026-05-01", status: "unpaid", is_recurring: true, recurring_day: 1 },
    { id: "pay-sukuk-may", debt_id: "debt-sukuk", title: "Sukuk Finance Reminder", amount: 1610.67, due_date: "2026-05-29", status: "unpaid", is_recurring: true, recurring_day: 29 },
    { id: "pay-tabby-statement", debt_id: "debt-tabby-statement", title: "Tabby Statement", amount: 1604.54, due_date: "2026-06-02", status: "unpaid" },
    { id: "pay-tabby-2-june", debt_id: "debt-tabby-later", title: "Tabby Installment", amount: 231.29, due_date: "2026-06-02", status: "unpaid" },
    { id: "pay-tabby-8-june", debt_id: "debt-tabby-later", title: "Tabby Installment", amount: 25.97, due_date: "2026-06-08", status: "unpaid" },
    { id: "pay-tabby-23-june", debt_id: "debt-tabby-later", title: "Tabby Installment", amount: 36.59, due_date: "2026-06-23", status: "unpaid" },
  ],
  goals: [
    { id: "goal-emergency", title: "Emergency Fund", target_amount: 1000, current_amount: 250, deadline: "2026-06-30", goal_type: "emergency" },
    { id: "goal-tabby", title: "Clear Tabby", target_amount: 2496.71, current_amount: 0, deadline: "2026-07-31", goal_type: "debt" },
  ],
};
