import type { FinanceState } from "./types";

export const seedState: FinanceState = {
  current_cash: 4247.56,
  settings: {
    survival_buffer: 1000,
    salary_day: 1,
    currency: "AED",
    theme: "light",
  },
  incomes: [
    {
      id: "income-salary",
      title: "Monthly Salary",
      amount: 8000,
      source: "Salary",
      income_date: "2026-05-01",
      is_recurring: true,
    },
  ],
  expenses: [],
  debts: [
    {
      id: "debt-sukuk",
      title: "Sukuk Finance",
      total_amount: 45000,
      remaining_amount: 40266.67,
      monthly_payment: 1610.67,
      due_date: "2026-05-30",
      due_day: 30,
      priority: "high",
      debt_type: "loan",
      status: "active",
    },
    {
      id: "debt-noon",
      title: "ENBD Noon Card",
      total_amount: 3714.05,
      remaining_amount: 3714.05,
      monthly_payment: 0,
      priority: "high",
      debt_type: "credit card",
      status: "active",
    },
    {
      id: "debt-mastercard",
      title: "Mastercard Titanium",
      total_amount: 6914.84,
      remaining_amount: 6914.84,
      monthly_payment: 0,
      priority: "high",
      debt_type: "credit card",
      status: "active",
    },
    {
      id: "debt-tabby-statement",
      title: "Tabby Statement",
      total_amount: 1604.54,
      remaining_amount: 1604.54,
      monthly_payment: 1604.54,
      due_date: "2026-06-02",
      priority: "medium",
      debt_type: "Tabby",
      status: "active",
    },
    {
      id: "debt-tabby-later",
      title: "Tabby Pay Later",
      total_amount: 892.17,
      remaining_amount: 892.17,
      monthly_payment: 0,
      priority: "medium",
      debt_type: "Tabby",
      status: "active",
    },
    {
      id: "debt-office",
      title: "Office Balance",
      total_amount: 4000,
      remaining_amount: 4000,
      monthly_payment: 500,
      priority: "medium",
      debt_type: "office",
      status: "active",
    },
  ],
  payments: [
    { id: "pay-sukuk", debt_id: "debt-sukuk", title: "Sukuk", amount: 1610.67, due_date: "2026-05-30", status: "unpaid" },
    { id: "pay-tabby", debt_id: "debt-tabby-statement", title: "Tabby", amount: 1604.54, due_date: "2026-06-02", status: "unpaid" },
    { id: "pay-flydubai", title: "Flydubai", amount: 231.29, due_date: "2026-06-02", status: "unpaid" },
    { id: "pay-noon-1", title: "Noon", amount: 25.97, due_date: "2026-06-08", status: "unpaid" },
    { id: "pay-noon-2", title: "Noon", amount: 36.59, due_date: "2026-06-23", status: "unpaid" },
  ],
  goals: [
    { id: "goal-emergency", title: "Emergency Fund", target_amount: 1000, current_amount: 250, deadline: "2026-06-30", goal_type: "emergency" },
    { id: "goal-tabby", title: "Clear Tabby", target_amount: 2496.71, current_amount: 0, deadline: "2026-07-31", goal_type: "debt" },
  ],
};
