import type { FinanceState } from "./types";

export const seedState: FinanceState = {
  current_cash: 4247.56,
  cash_accounts: [{ id: "real-account-nbd", title: "NBD/current bank balance", amount: 4247.56, include_in_safe: true }],
  assets: [
    {
      id: "real-asset-binance",
      title: "Binance USDT Asset",
      amount: 300,
      currency: "USDT",
      include_in_safe: false,
      notes: "Crypto asset only. Not included in Safe to Spend.",
    },
  ],
  settings: {
    survival_buffer: 500,
    salary_day: 1,
    currency: "AED",
    theme: "light",
    profile_version: 6,
  },
  incomes: [
    {
      id: "real-income-salary",
      title: "Monthly Salary",
      amount: 8000,
      source: "Salary",
      income_date: "2026-05-01",
      is_recurring: true,
      notes: "Recurring monthly salary.",
    },
  ],
  expenses: [],
  debts: [
    {
      id: "real-debt-sukuk",
      title: "Sukuk Finance Loan",
      total_amount: 45000,
      remaining_amount: 40266.67,
      monthly_payment: 1610.67,
      due_day: 30,
      reminder_day: 29,
      priority: "high",
      debt_type: "Finance Loan",
      icon: "bank",
      status: "active",
      notes: "Actual due date every month 30th. App reminder one day early on 29th.",
    },
    {
      id: "real-debt-noon",
      title: "ENBD Noon Credit Card",
      total_amount: 3714.05,
      remaining_amount: 3714.05,
      used_amount: 3714.05,
      monthly_payment: 0,
      due_day: 10,
      reminder_day: 9,
      priority: "high",
      debt_type: "Credit Card",
      icon: "card",
      status: "active",
    },
    {
      id: "real-debt-mastercard",
      title: "Emirates NBD Titanium Mastercard",
      total_amount: 6914.84,
      remaining_amount: 6914.84,
      used_amount: 6914.84,
      monthly_payment: 0,
      due_day: 3,
      reminder_day: 2,
      priority: "high",
      debt_type: "Credit Card",
      icon: "card",
      status: "active",
    },
    {
      id: "real-debt-aafaq",
      title: "Aafaq Credit Card",
      total_amount: 10000.9,
      remaining_amount: 1376,
      used_amount: 1376,
      available_limit: 8624.9,
      total_limit: 10000.9,
      monthly_payment: 0,
      priority: "high",
      debt_type: "Credit Card",
      icon: "card",
      status: "active",
      notes: "Total limit approx AED 10,000.90.",
    },
    {
      id: "real-debt-tabby-statement",
      title: "Tabby Statement",
      total_amount: 1604.54,
      remaining_amount: 1604.54,
      monthly_payment: 1604.54,
      due_date: "2026-06-02",
      priority: "high",
      debt_type: "Tabby / Installment",
      icon: "tabby",
      status: "active",
    },
    {
      id: "real-debt-tabby-later",
      title: "Tabby Pay Later / Installments",
      total_amount: 892.17,
      remaining_amount: 892.17,
      monthly_payment: 0,
      priority: "high",
      debt_type: "Installment",
      icon: "tabby",
      status: "active",
    },
    {
      id: "real-debt-office",
      title: "Office Loan / Office Balance",
      total_amount: 4000,
      remaining_amount: 4000,
      monthly_payment: 500,
      due_day: 1,
      reminder_day: 1,
      priority: "medium",
      debt_type: "Office Loan",
      icon: "office",
      status: "active",
      notes: "AED 500 monthly deduction from salary.",
    },
  ],
  payments: [
    { id: "real-pay-rent-may", title: "Rent Payment", amount: 4200, due_date: "2026-05-10", status: "unpaid", category: "Rent", priority: "critical", is_recurring: true, recurring_day: 10, reminder_day: 9, notes: "Current cash is reserved for this rent payment." },
    { id: "real-pay-mastercard-may", debt_id: "real-debt-mastercard", title: "Emirates NBD Titanium Reminder", amount: 6914.84, due_date: "2026-05-02", status: "unpaid", category: "Debt Payment", priority: "high", is_recurring: true, recurring_day: 2, reminder_day: 2 },
    { id: "real-pay-noon-may", debt_id: "real-debt-noon", title: "ENBD Noon Card Reminder", amount: 3714.05, due_date: "2026-05-09", status: "unpaid", category: "Debt Payment", priority: "high", is_recurring: true, recurring_day: 9, reminder_day: 9 },
    { id: "real-pay-office-may", debt_id: "real-debt-office", title: "Office Loan Deduction", amount: 500, due_date: "2026-05-01", status: "unpaid", category: "Office Deduction", priority: "medium", is_recurring: true, recurring_day: 1, reminder_day: 1 },
    { id: "real-pay-sukuk-may", debt_id: "real-debt-sukuk", title: "Sukuk Finance Reminder", amount: 1610.67, due_date: "2026-05-29", status: "unpaid", category: "Debt Payment", priority: "high", is_recurring: true, recurring_day: 29, reminder_day: 29 },
    { id: "real-pay-tabby-statement", debt_id: "real-debt-tabby-statement", title: "Tabby Statement", amount: 1604.54, due_date: "2026-06-02", status: "unpaid", category: "Debt Payment", priority: "high" },
    { id: "real-pay-tabby-2-june", debt_id: "real-debt-tabby-later", title: "Tabby Installment", amount: 231.29, due_date: "2026-06-02", status: "unpaid", category: "Debt Payment", priority: "high" },
    { id: "real-pay-tabby-8-june", debt_id: "real-debt-tabby-later", title: "Tabby Installment", amount: 25.97, due_date: "2026-06-08", status: "unpaid", category: "Debt Payment", priority: "medium" },
    { id: "real-pay-tabby-23-june", debt_id: "real-debt-tabby-later", title: "Tabby Installment", amount: 36.59, due_date: "2026-06-23", status: "unpaid", category: "Debt Payment", priority: "medium" },
  ],
  payment_history: [],
  goals: [],
};
